### ISSUE TITLE
Things Remote can't do

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/pymmcore-plus#112]
keeping track of things remote currently can't do:

1. Use MDA at all
    - the mda object isn't properly exposed
2. use `devicePropertyChanged` signals:
    - https://github.com/tlambert03/pymmcore-plus/blob/717a74330d01903ea7a4062a000752991f1074e2/pymmcore_plus/remote/server/_pyrocore.py#L34-L36

**Comment by tlambert03** [comment]
3. generally work! :) #43 (linking as a reminder/major hindrance even if 1 & 2 are fixed)

**Comment by tlambert03** [comment]
removed remote in #208
