### ISSUE TITLE
Have a mechanism to update the `uid` of MDASequences when run

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/pymmcore-plus#129]
Currently if you make an MDASequence and then run it multiple times then they will share the same `uid` and this can lead to issues downstream (e.g. in displaying in napari-mircomanager).

While the description of the experiment is the same, these colleciton runs should have different ids because they have been run at different times and are thus distinct from eachother.

**Comment by tlambert03** [comment]
I think maybe that's a napari-micromanager issue rather than a uid issue.  Napari micromanager could perhaps add a timestamp to it to avoid those conflicts
