### ISSUE TITLE
task: rename `startContinuousSequenceAcquisition` and `startSequenceAcquisition` events

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/pymmcore-plus#162]
The following events should be renamed to stay in keeping with the pattern of the other names:

`startContinuousSequenceAcquisition` -> `continuousSequenceAcquisitionStarted`
`startSequenceAcquisition` -> `sequenceAcquisitionStarted`
`stopSequenceAcquisition` -> `sequenceAcquisitionStopped`

not sure if that will require changes in pymmcore-widgets or napari-micromanager?

cc @fdrgsp

**Comment by fdrgsp** [comment]
Agree! Yes there are a couple of widgets that will have to be fixed. I'll soon open a PR to change the names here and then when merged I'll fix the widgets.
