### ISSUE TITLE
Some readme.md links are bad

### ISSUE THREAD

**Issue by HazenBabcock** [pymmcore-plus/pymmcore-plus#187]
You have a number of links in the README.md file like this:
`http://127.0.0.1:8000/pymmcore-plus/examples/mda/`

At least for me these don't work. It looks like they are pointing to a local server on your development machine?

**Comment by tlambert03** [comment]
Lol, thanks for letting us know @HazenBabcock 

The links should point to https://pymmcore-plus.github.io/pymmcore-plus/contributing/ and any of the examples like https://pymmcore-plus.github.io/pymmcore-plus/examples/mda/
