### ISSUE TITLE
How should code that uses pymmcore-plus emit log messages?

### ISSUE THREAD

**Issue by kmdouglass** [pymmcore-plus/pymmcore-plus#238]
Hello!

We ran into an interesting problem today that comes down to the question of how our code, which depends on pymmcore-plus, should configure and emit log messages.

Normally, we use the `logging` module in the Python standard library to handle logging. However, we saw that `pymmcore-plus` is using a third party library called `loguru`. We don't necessarily want to use `loguru` because relying on a dependency of a dependency (pymmcore-plus, in this case) is usually not recommended practice. For example, we'd have to change all our code if pymmcore-plus ever dropped `loguru` in the future, and for us the standard library's `logging` is sufficient enough that'd we'd like to keep it.

But can the standard library logger and loguru work together in such a scenario? @wl-stepp noticed some funny behaviors using both, but we weren't too sure if it was a real problem or just something we didn't understand.

What is the advice you give to others wanting to log messages from their code when using pymmcore-plus?

Thanks!

**Comment by tlambert03** [comment]
> We don't necessarily want to use loguru because relying on a dependency of a dependency (pymmcore-plus, in this case) is usually not recommended practice.

yep that certainly makes sense.  I would only recommend you do that if there was a public API (and the third party dependency) was hidden to you behind some API.  

> For example, we'd have to change all our code if pymmcore-plus ever dropped loguru in the future,

unless there was an API that we supported and tested... which is the only way I'd suggest.  Currently, our logger is hidden, for exactly this reason, but now's a good time to discuss it.

> @wl-stepp noticed some funny behaviors using both, but we weren't too sure if it was a real problem or just something we didn't understand.

I would like to hear more about that.  can you elaborate?  I'm not an expert here, so there could be some funny interplay.  Loguru does wrap the standard library, so i can certainly imagine weirdness.

> What is the advice you give to others wanting to log messages from their code when using pymmcore-plus?

This is the first time it's come up, so let's figure it out.  
I did write up a bit on how pymmcore-plus writes logs here: https://pymmcore-plus.github.io/pymmcore-plus/guides/logging/ (but it doesn't cover how you should write your own while using pymmcore-plus)

A couple (nice) things to point out:
- pymmcore-plus unifies logs emitted by CMMCore and by the python side into a single file
- that file is stored in a default user-space directory (See docs for details)
- you can monitor logs in another process easily with `mmcore logs --tail`

**However (tldr)** I'm not at all married to loguru and we don't really use its API very heavily at all. So, I'd be happy to just drop it and use a standard library logger if you have any preference for that.  We should also discuss how to unify logging that happens from core with external code.  Do you *want* to have a `core.logger.log()` API, in the interest of putting all the logs in the same place?  Or would you prefer to just have your own logs, and only really care that whatever we're doing doesn't get in the way of it?

**Comment by wl-stepp** [comment]
So logging with the standard library seems to work after a couple of changes, maybe something with environment variables. I will try to replicate that.

There is something that I can replicate though. If a function that is connected to an mmcore.mda Slot raises an error, that seems to be ignored.

So this doesn't show the error
```python
from pymmcore_plus import CMMCorePlus
import numpy as np
from useq import MDAEvent, MDASequence

mmc = CMMCorePlus()
mmc.loadSystemConfiguration()

def on_frame_ready(im: np.ndarray, event:MDAEvent):
    print("frame ready")
    raise Exception

mmc.mda.events.frameReady.connect(on_frame_ready)

seq = MDASequence(
        channels=["Cy5"],
        time_plan={"interval": 1.5, "loops": 2},
    )

mmc.run_mda(seq)
```

Output:
```
2023-08-04 17:02:45.459 | INFO     | pymmcore_plus.mda._runner:_prepare_to_run:209 - MDA Started: Multi-Dimensional Acquisition ▶ nt: 2, np: 0, ng: 0, nc: 1, nz: 0
2023-08-04 17:02:45.463 | INFO     | pymmcore_plus.mda._runner:run:171 - index={'t': 0, 'c': 0} channel=Channel(config='Cy5') exposure=None min_start_time=0.0 pos_name=None x_pos=None y_pos=None z_pos=None properties=None global_index=0 metadata={}
frame ready
2023-08-04 17:02:46.965 | INFO     | pymmcore_plus.mda._runner:run:171 - index={'t': 1, 'c': 0} channel=Channel(config='Cy5') exposure=None min_start_time=1.5 pos_name=None x_pos=None y_pos=None z_pos=None properties=None global_index=1 metadata={}
frame ready
2023-08-04 17:02:46.985 | INFO     | pymmcore_plus.mda._runner:_finish_run:296 - MDA Finished: Multi-Dimensional Acquisition ▶ nt: 2, np: 0, ng: 0, nc: 1, nz: 0
```

**Comment by tlambert03** [comment]
I'm already half-way done with a PR to remove loguru.  There's no good reason to use it :).  So don't put too much more effort into debugging.

interesting about the callbacks though.  not terribly surprising, with Qt, threading, etc... but is that something you haven't seen before?

**Comment by tlambert03** [comment]
see #239.  you can give it a shot if you want, and I'll try your code example now

**Comment by tlambert03** [comment]
> There is something that I can replicate though. If a function that is connected to an mmcore.mda Slot raises an error, that seems to be ignored.

oh I'm sorry @wl-stepp... I missed the point here.

That's actually because we catch (and weren't logging) errors here:

https://github.com/pymmcore-plus/pymmcore-plus/blob/f098e609297461535f902736ffdbbd51ebdb17fd/src/pymmcore_plus/mda/_runner.py#L191-L200

I'll add them to the logs in #239

**Comment by tlambert03** [comment]
ok, funny that the windows CI isn't catching that 🤔

**Comment by tlambert03** [comment]
removing that character in https://github.com/pymmcore-plus/useq-schema/pull/126#issuecomment-1665849576

**Comment by kmdouglass** [comment]
@tlambert03 thanks so much for the fast response! I wasn't expecting you to remove loguru, though I do approve of removing a little-used dependency.

**Comment by tlambert03** [comment]
yeah, I know you weren't.  but yep, it's the right thing to do 👍

will merge #239  shortly, which will close this issue.  but do let me know if either of you also want one of the following added options:

1. the pymmcore_plus._logger.logger instance to be made publicly available as `pymmcore_plus.logger`
2. have the logger be available on the CMMCorePlus

**Comment by kmdouglass** [comment]
Thanks Talley.

>  but do let me know if either of you also want one of the following added options:

I don't for the moment need either option, and in the worst case I can always get a logger by its name through logger.getLogger. So for the moment I'd say neither is necessary.

Cheers!
