### ISSUE TITLE
Documentation of events might be out of date.

### ISSUE THREAD

**Issue by wl-stepp** [pymmcore-plus/pymmcore-plus#259]
https://github.com/pymmcore-plus/pymmcore-plus/blob/b2a2f524d9a743c84b234dced9b0045f68551fe3/src/pymmcore_plus/core/events/_protocol.py#L67C1-L79C1

The documentation states that the events can be directly accessed from the core. I have to do
```python
core.events.exposureChanged.connect(my_callback)
```

Docs:
To connect to the `onExposureChanged` event emitted by MMCore, you
would connect to the `exposureChanged` signal on this class:

```python
from pymmcore_plus import CMMCorePlus

core = CMMCorePlus()

def on_exposure_changed(device: str, new_exposure: float):
    print(f"Exposure changed for {device} to {new_exposure}")

core.exposureChanged.connect(my_callback)

**Comment by tlambert03** [comment]
indeed thanks!  At first we put all the signals on the core object itself.  needs updating
