### ISSUE TITLE
Consider making the first instantiated CMMCorePlus object  the global instance

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/pymmcore-plus#261]
Proposing putting the logic in instance():

```python
        global _instance
        if _instance is None:
            _instance = cls()
```

into the __init__ instead, so that the first CMMCorePlus is the global instance (you can still make others, for testing and stuff... but this just makes it a little easier to make the "first/main" one)

@ianhi . thoughts?

**Comment by ianhi** [comment]
I'm definitely for this - at least for common use cases. In which case I think this is strictly a good thing to add some guard rails to make sure you always have the right thing. But need to continue to support the use case I've seen a few times on image.sc where people keep multiple core instances for when they have complicated custom setups/very high performance things.
